site_name: LogU Sawtooth Container Transaction Model
repo_url: https://github.com/J0nasW/logu-sawtooth-container
nav:
    - Home: index.md
    - User Guide:
        - Installation: installation.md
        - MyContainer App: mycontainer.md
    - About: about.md
theme: readthedocs
